### ISSUE TITLE
Upgrade provider to 6.0.1

### ISSUE THREAD

**Issue by DevyankShaw** [ajaynonstopio/connectivity_wrapper#12]
Hi @ajaykumargithub2114 request to upgrade the provider package version, it's breaking my project build

**Comment by vptcnt** [comment]
Same here...

**Comment by govindmaheshwari2** [comment]
@DevyankShaw @vptcnt try this : https://pub.dev/packages/connectivity_checker

**Comment by maxim-ivanchuk-idf** [comment]
++++

**Comment by ProjectAJ14** [comment]
The new version is released 1.1.0
