### ISSUE TITLE
I have migrated to null safety and targeted to Android 12 Not able to run the app any solution will help

### ISSUE THREAD

**Issue by pranoy-smarthealth** [ajaynonstopio/connectivity_wrapper#13]
The following _CastError was thrown building ConnectivityScreenWrapper(dirty, dependencies: [_InheritedProviderScope<ConnectivityStatus>, MediaQuery]):
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

**Comment by ProjectAJ14** [comment]
@pranoy-smarthealth Can you please share the output of `flutter doctor`?

**Comment by JulioRennan** [comment]
Hi there i had the same problem after migrate the project to null safety and i'm solved this problem cleaning ao pub cache with:
`flutter pub cache clean`

**Comment by shahenshamohd** [comment]
> Hi there i had the same problem after migrate the project to null safety and i'm solved this problem cleaning ao pub cache with: `flutter pub cache clean`
Am not  able to fix the issue  while doing this command.
