### ISSUE TITLE
AddressCheckOptions isn't defined

### ISSUE THREAD

**Issue by vptcnt** [ajaynonstopio/connectivity_wrapper#18]
Hello, 

With the last version, 1.1.2, we got the message:
The function 'AddressCheckOptions' isn't defined.
Try importing the library that defines 'AddressCheckOptions', correcting the name to the name of an existing function, or defining a function named 'AddressCheckOptions'.

when we used the following code:
```dart
ConnectivityWrapper.instance.addresses = [
    AddressCheckOptions(
      InternetAddress('XX.XX.XX.XX'),
      port: 80,
      timeout: const Duration(seconds: 10),
    ),
  ];
```

Seems it misses the export of the models.

V.

**Comment by ProjectAJ14** [comment]
```
ConnectivityWrapper.instance.addresses = [
    AddressCheckOptions(
      address: InternetAddress('1.1.1.1'),
      port: 80,
      timeout: const Duration(seconds: 10),
    ),
  ];
```
Ohh! I forgot to export  `AddressCheckOptions`. This is fixed in 1.1.3
