### ISSUE TITLE
Please update provider dependency

### ISSUE THREAD

**Issue by tejaeightfolds** [ajaynonstopio/connectivity_wrapper#2]
Compiler message:
../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_wrapper-1.0.2/lib/src/widgets/connectivity_app_wrapper_widget.dart:19:7: Error: No named parameter with the name 'builder'.
      builder: (context) => ConnectivityProvider().connectivityStream,
      ^^^^^^^
../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.0.0/lib/src/async_provider.dart:80:3: Context: Found this candidate, but the arguments don't match.
  StreamProvider({
  ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/bharadwaj/sdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/bharadwaj/sdk/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by aleksandar-radivojevic** [comment]
Any updates on this??

**Comment by ProjectAJ14** [comment]
Updated to `provider: ^4.3.2`.
