### ISSUE TITLE
How to handle api calls with Dio using this package ?

### ISSUE THREAD

**Issue by maheshperi19** [ajaynonstopio/connectivity_wrapper#4]
Good package. It is checking network connectivity very well. But how to handle api calls with Dio using this package. 

I am able to check user is online or offline. But If i call api without internet, getting exception.

If provide any callback method to handle UI when exception, that is also fine.

Any suggestions would help me in this.

Thanks.

**Comment by maheshperi** [comment]
Thank you. I solved the problem.

For Network error handling with Dio, i am using below pacakage.
provider_utilities:
    git:
      url: https://github.com/quantosapplications/flutter_provider_utilities.git

For internet status change, i am using ConnectivityWrapper.instance.onStatusChange.listen method to call again api when user is come to online.

**Comment by ProjectAJ14** [comment]
@MaheshPeri19 You can use the try-catch for Timeout exception and the handle it on you basis

**Comment by maheshperi19** [comment]
Thanks for your reply.

Yes. I am handling with try-catch block.
