### ISSUE TITLE
Null Safety ConnectivityScreenWrapper with ProviderScope

### ISSUE THREAD

**Issue by katsikas-kostas** [ajaynonstopio/connectivity_wrapper#8]
Something is off here. 
```
The following _CastError was thrown building ConnectivityScreenWrapper(dirty, dependencies: [_InheritedProviderScope<ConnectivityStatus>, MediaQuery]):
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast
```

https://github.com/ajaynonstopio/connectivity_wrapper/blob/60869c29af341c1e95529f7af3342fe763ebb321/lib/src/widgets/connectivity_screen_wrapper.dart#L94

**Comment by vptcnt** [comment]
Same error.

A way to fix :

ConnectivityScreenWrapper.dart
```dart
return AbsorbPointer(
      absorbing: (disableInteraction && isOffline),
      child: Stack(
        children: (<Widget>[    // Remove ?
          child!,   // Add ! or maybe a test (if child != null) child!
          if (disableInteraction && isOffline)
            if (disableWidget != null) disableWidget!,  // Add !
          offlineWidget,
        ]) as List<Widget>,
      ),
    );
```

ConnectivityWidgetWrapper.dart
```dart
  if (stacked)
      return Stack(
        children: (<Widget>[    // Remove ?
          child!,   // Add ! or maybe a test (if child != null) child!
          disableInteraction && isOffline
              ? Column(
                  children: <Widget>[
                    Flexible(
                      child: Container(
                        decoration: decoration ??
                            BoxDecoration(
                              color: Colors.black38,
                            ),
                      ),
                    )
                  ],
                )
              : EmptyContainer(),
          isOffline ? finalOfflineWidget : EmptyContainer(),
        ]) as List<Widget>,
      );
```

**Comment by ProjectAJ14** [comment]
@katsikas-kostas I was not able to reproduce this issue. Can you please tell me your current flutter version?

**Comment by vptcnt** [comment]
2.0.5

**Comment by larinnim** [comment]
2.0.6 same issue

**Comment by larinnim** [comment]
The workaround is to set stacked to false.
 'ConnectivityWidgetWrapper(
          stacked: false,')

**Comment by MDSADABWASIM** [comment]
I was also facing the issue, and this https://github.com/ajaynonstopio/connectivity_wrapper/issues/8#issuecomment-819902761 
solved the issue.

**Comment by alr2413** [comment]
i've the same issue.

**Comment by shahenshamohd** [comment]
> Same error.
> 
> A way to fix :
> 
> ConnectivityScreenWrapper.dart
> 
> ```dart
> return AbsorbPointer(
>       absorbing: (disableInteraction && isOffline),
>       child: Stack(
>         children: (<Widget>[    // Remove ?
>           child!,   // Add ! or maybe a test (if child != null) child!
>           if (disableInteraction && isOffline)
>             if (disableWidget != null) disableWidget!,  // Add !
>           offlineWidget,
>         ]) as List<Widget>,
>       ),
>     );
> ```
> 
> ConnectivityWidgetWrapper.dart
> 
> ```dart
>   if (stacked)
>       return Stack(
>         children: (<Widget>[    // Remove ?
>           child!,   // Add ! or maybe a test (if child != null) child!
>           disableInteraction && isOffline
>               ? Column(
>                   children: <Widget>[
>                     Flexible(
>                       child: Container(
>                         decoration: decoration ??
>                             BoxDecoration(
>                               color: Colors.black38,
>                             ),
>                       ),
>                     )
>                   ],
>                 )
>               : EmptyContainer(),
>           isOffline ? finalOfflineWidget : EmptyContainer(),
>         ]) as List<Widget>,
>       );
> ```

Try to replace this code AbsorbPointer(
      absorbing: (disableInteraction && isOffline),
      child: Stack(
        children: (<Widget?>[
          if (child != null) child,
          if (disableInteraction && isOffline)
            if (disableWidget != null) disableWidget,
          _offlineWidget,
        ]) as List<Widget>,
      ),
    );

with  this code AbsorbPointer(
      absorbing: (disableInteraction && isOffline),
      child: Stack(
        children: (<Widget>[
          if (child != null) child!,
          if (disableInteraction && isOffline)
            if (disableWidget != null) disableWidget!,
          _offlineWidget,
        ]) as List<Widget>,
      ),
    ); 
and run the command flutter clean and flutter run.
